language: r
sudo: false
cache: packages
warnings_are_errors: true
r: bioc-devel
before_script: cd MLExpResso
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("MLExpResso")'

