language: r
sudo: true
cache: packages
r: bioc-devel
before_install: 
  - cd MLExpResso
r_github_packages: geneticsMiNIng/MLGenSigdata/MLExpRessodata
r_binary_packages:
  - dplyr 
  - ggplot2 
  - ggrepel 
  - ggthemes
  - gridExtra
  - reshape
  - reshape2
  - roxygen2 
  - scales
  - stringr 

